Rem Copyrigth (c) 2000 by Oracle Corporation
Rem NAME
Rem UTLSAMPL.SQL
Rem FUNCTION
Rem NOTES
Rem MODIFIED
Rem 
rem $Header: utlsamp.sql 7020100.1 22:14:24 cli Generic base $sqlbld.sql
rem 
SET TERMOUT OFF
SET ECHO OFF

rem CONGDON Invoked in RDBMS a
rem build time.
rem OATES: Created 20-Nov-22

GRAN CONNECT, RESOURCE, UNLIMITED TABLESPACE TO LIQUIDACIONES IDENTIFIED BY TIGER;
ALTER USER LIQUIDACIONES DEFAULT TABLESPACE USERS;
ALTER USER LIQUIDACIONES TEMPORARY TABLESPACE TEMP;
ALTER USER LIQUIDACIONES/TIGER
DROP TABLE DOCUMENTO;
CREATE TABLE DOCUMENTO;
CREATE TABLE PRE_LIQUIDACION; -- detalle de las preliquidaciones